In [11]:
import pandas as pd

import plotly.express as px

In [3]:
df = pd.read_csv("data/SaaS-Sales_aws.csv")

df

,Row ID,Order ID,Order Date,Date Key,Contact Name,Country,City,Region,Subregion,Customer,Customer ID,Industry,Segment,Product,License,Sales,Quantity,Discount,Profit
0,1,EMEA-2022-152156,11/9/2022,20221109,Nathan Bell,Ireland,Dublin,EMEA,UKIR,Chevron,1017,Energy,SMB,Marketing Suite,16GRM07R1K,261.9600,2,0.00,41.9136
1,2,EMEA-2022-152156,11/9/2022,20221109,Nathan Bell,Ireland,Dublin,EMEA,UKIR,Chevron,1017,Energy,SMB,FinanceHub,QLIW57KZUV,731.9400,3,0.00,219.5820
2,3,AMER-2022-138688,6/13/2022,20220613,Deirdre Bailey,United States,New York City,AMER,NAMER,Phillips 66,1056,Energy,Strategic,FinanceHub,JI6BVL70HQ,14.6200,2,0.00,6.8714
3,4,EMEA-2021-108966,10/11/2021,20211011,Zoe Hodges,Germany,Stuttgart,EMEA,EU-WEST,Royal Dutch Shell,1031,Energy,SMB,ContactMatcher,DE9GJKGD44,957.5775,5,0.45,-383.0310
4,5,EMEA-2021-108966,10/11/2021,20211011,Zoe Hodges,Germany,Stuttgart,EMEA,EU-WEST,Royal Dutch Shell,1031,Energy,SMB,Marketing Suite - Gold,OIF7NY23WD,22.3680,2,0.20,2.5164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,EMEA-2020-110422,1/22/2020,20200122,Dan Allan,Germany,Hamburg,EMEA,EU-WEST,Johnson & Johnson,1055,Healthcare,SMB,SaaS Connector Pack,ETHXMB5TMD,25.2480,3,0.20,4.1028
9990,9991,AMER-2023-121258,2/27/2023,20230227,Anthony Sanderson,United States,Milwaukee,AMER,NAMER,American Express,1005,Finance,SMB,SaaS Connector Pack,LYHOKTRY7L,91.9600,2,0.00,15.6332
9991,9992,AMER-2023-121258,2/27/2023,20230227,Anthony Sanderson,United States,Milwaukee,AMER,NAMER,American Express,1005,Finance,SMB,Site Analytics,I5SVMI6M88,258.5760,2,0.20,19.3932
9992,9993,AMER-2023-121258,2/27/2023,20230227,Anthony Sanderson,United States,Milwaukee,AMER,NAMER,American Express,1005,Finance,SMB,Support,JHLW4P6LQ2,29.6000,4,0.00,13.3200
9993,9994,AMER-2023-119914,5/5/2023,20230505,Jasmine Springer,United States,Dallas,AMER,NAMER,Comcast,1022,Communications,SMB,OneView,3NTBV9B3PS,243.1600,2,0.00,72.9480

In [4]:
df.shape

(9994, 19)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 19 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Row ID        9994 non-null   int64
 1   Order ID      9994 non-null   object
 2   Order Date    9994 non-null   object
 3   Date Key      9994 non-null   int64
 4   Contact Name  9994 non-null   object
 5   Country       9994 non-null   object
 6   City          9994 non-null   object
 7   Region        9994 non-null   object
 8   Subregion     9994 non-null   object
 9   Customer      9994 non-null   object
 10  Customer ID   9994 non-null   int64
 11  Industry      9994 non-null   object
 12  Segment       9994 non-null   object
 13  Product       9994 non-null   object
 14  License       9994 non-null   object
 15  Sales         9994 non-null   float64
 16  Quantity      9994 non-null   int64
 17  Discount      9994 non-null   float64
 18  Profit        9994 non-null   float64
dtypes: float64(3), int64(4), object(12)
memory usage: 1.4+ MB

In [6]:
df.describe()

,Row ID,Date Key,Customer ID,Sales,Quantity,Discount,Profit
count,9994.000000,9.994000e+03,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,2.021803e+07,1049.771963,229.858001,3.789574,0.156203,28.656896
std,2885.163629,1.123898e+04,29.719388,623.245101,2.225110,0.206452,234.260108
min,1.000000,2.020010e+07,1001.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,2.021052e+07,1024.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,2.022063e+07,1049.000000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,2.023052e+07,1076.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,2.023123e+07,1101.000000,22638.480000,14.000000,0.800000,8399.976000

In [17]:
def date_format(df):
    df["Order Date"]= pd.to_datetime(df["Order Date"])
    df["month_name"] = df["Order Date"].dt.month_name()
    df["month"] = df["Order Date"].dt.month
    df["year"] = df["Order Date"].dt.year
    df["day_name"] = df["Order Date"].dt.day_name()
    df["weekday"] = df["Order Date"].dt.weekday
    df["day"] = df["Order Date"].dt.day
    df["quarter"] = df["Order Date"].dt.quarter

    return df

date_format(df)

,Row ID,Order ID,Order Date,Date Key,Contact Name,Country,City,Region,Subregion,Customer,...,Quantity,Discount,Profit,month_name,month,year,day_name,weekday,day,quarter
0,1,EMEA-2022-152156,2022-11-09,20221109,Nathan Bell,Ireland,Dublin,EMEA,UKIR,Chevron,...,2,0.00,41.9136,November,11,2022,Wednesday,2,9,4
1,2,EMEA-2022-152156,2022-11-09,20221109,Nathan Bell,Ireland,Dublin,EMEA,UKIR,Chevron,...,3,0.00,219.5820,November,11,2022,Wednesday,2,9,4
2,3,AMER-2022-138688,2022-06-13,20220613,Deirdre Bailey,United States,New York City,AMER,NAMER,Phillips 66,...,2,0.00,6.8714,June,6,2022,Monday,0,13,2
3,4,EMEA-2021-108966,2021-10-11,20211011,Zoe Hodges,Germany,Stuttgart,EMEA,EU-WEST,Royal Dutch Shell,...,5,0.45,-383.0310,October,10,2021,Monday,0,11,4
4,5,EMEA-2021-108966,2021-10-11,20211011,Zoe Hodges,Germany,Stuttgart,EMEA,EU-WEST,Royal Dutch Shell,...,2,0.20,2.5164,October,10,2021,Monday,0,11,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,EMEA-2020-110422,2020-01-22,20200122,Dan Allan,Germany,Hamburg,EMEA,EU-WEST,Johnson & Johnson,...,3,0.20,4.1028,January,1,2020,Wednesday,2,22,1
9990,9991,AMER-2023-121258,2023-02-27,20230227,Anthony Sanderson,United States,Milwaukee,AMER,NAMER,American Express,...,2,0.00,15.6332,February,2,2023,Monday,0,27,1
9991,9992,AMER-2023-121258,2023-02-27,20230227,Anthony Sanderson,United States,Milwaukee,AMER,NAMER,American Express,...,2,0.20,19.3932,February,2,2023,Monday,0,27,1
9992,9993,AMER-2023-121258,2023-02-27,20230227,Anthony Sanderson,United States,Milwaukee,AMER,NAMER,American Express,...,4,0.00,13.3200,February,2,2023,Monday,0,27,1
9993,9994,AMER-2023-119914,2023-05-05,20230505,Jasmine Springer,United States,Dallas,AMER,NAMER,Comcast,...,2,0.00,72.9480,May,5,2023,Friday,4,5,2

In [43]:
df["Product"].value_counts()

Product
ContactMatcher                1842
Support                       1560
FinanceHub                     981
SaaS Connector Pack            957
Site Analytics                 889
Marketing Suite - Gold         846
ChatBot Plugin                 796
Data Smasher                   775
OneView                        466
SaaS Connector Pack - Gold     254
Marketing Suite                228
Storage                        217
Big Ol Database                115
Alchemy                         68
Name: count, dtype: int64

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 26 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Row ID        9994 non-null   int64
 1   Order ID      9994 non-null   object
 2   Order Date    9994 non-null   datetime64[ns]
 3   Date Key      9994 non-null   int64
 4   Contact Name  9994 non-null   object
 5   Country       9994 non-null   object
 6   City          9994 non-null   object
 7   Region        9994 non-null   object
 8   Subregion     9994 non-null   object
 9   Customer      9994 non-null   object
 10  Customer ID   9994 non-null   int64
 11  Industry      9994 non-null   object
 12  Segment       9994 non-null   object
 13  Product       9994 non-null   object
 14  License       9994 non-null   object
 15  Sales         9994 non-null   float64
 16  Quantity      9994 non-null   int64
 17  Discount      9994 non-null   float64
 18  Profit        9994 non-null   float64
 19  month_name    9994 non-null   object
 20  month         9994 non-null   int32
 21  year          9994 non-null   int32
 22  day_name      9994 non-null   object
 23  weekday       9994 non-null   int32
 24  day           9994 non-null   int32
 25  quarter       9994 non-null   int32
dtypes: datetime64[ns](1), float64(3), int32(5), int64(4), object(13)
memory usage: 1.8+ MB

# DISCOVER ANALYSIS

In [31]:
print(df["Order Date"].min())
print(df["Order Date"].max())

2020-01-04 00:00:00
2023-12-31 00:00:00

In [15]:
df_sales_by_company = df.groupby("Customer")["Sales"].sum().round(0).reset_index().sort_values(by="Sales",ascending=False)

fig = px.bar(df_sales_by_company, x="Customer", y="Sales", barmode="group", title="Sales by company")
fig.show()

In [ ]:
df_sales_by_months = df.groupby("month")["Sales"].sum().round().reset_index().sort_values(by="month")

fig = px.line(df_sales_by_months, x="month", y='Sales', title='Sales by months')
fig.update_layout(xaxis={'dtick':1})
fig.show()